### PR TITLE
Add ingress data source and move to swagger docs for ingress

### PR DESCRIPTION
**Pull request by dak1n1**
This PR pulls in the work done by @thommaa to add the ingress data source: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/615

It also adds a few syntax fixes and swagger docs to the ingress data source and resource.

### CODE REVIEW

**Comment by dak1n1** [comment]
I have to make this a non-draft PR for TC to test it. It's not ready for review yet.

**Comment by dak1n1** [comment]
@jrhouston gave a :+1: in Slack for the swagger doc changes, so I'll merge as soon as tests pass.

**Comment by meysammeisam** [comment]
@dak1n1 Good job, Do you have any estimation when these changes are gonna be released?

**Comment by dak1n1** [comment]
@meysammeisam since it's a non-breaking change, it can be released right away. Thanks for bringing it to my attention. I'll start that process and with any luck, it will be released later today. :)

**Comment by meysammeisam** [comment]
@dak1n1 Thanks :)

**Pull request merged**
