### PR TITLE
Possible fix for deployment strategy

### PR DESCRIPTION
**Pull request by xmackex**
Possible fix for #260
I'm not a experienced Go developer, bu I needed `strategy` to work properly.
This fix works for me, but was not able to make any verbose testing.

### CODE REVIEW

**Comment by pasali** [comment]
@alexsomesan what do you think about this PR ? A lot of people having this issue.

**Comment by dploeger** [comment]
@alexsomesan Ping 😉

**Comment by dploeger** [comment]
@alexsomesan there is another pr to fix this and it already has tests. Could you please check out #372 as well and perhaps first? Thanks.

**Comment by xmackex** [comment]
@campbel @alexsomesan 
This [PR](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/372) looks much better, so closing mina in favor of 372

**Pull request closed without merging**
