### PR TITLE
Add run_as_group to container security contexts attributes

### PR DESCRIPTION
**Pull request by pdecat**
As per @jhoblitt [request](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/249#issuecomment-486476881), reviving this one.

Needs rebase.

For reference, [the `RunAsGroup` feature has been promoted to beta and enabled by default in kubernetes 1.14](https://github.com/kubernetes/kubernetes/pull/73007).

### CODE REVIEW

**Comment by pdecat** [comment]
Rebased on master.

**Comment by pdecat** [comment]
As already noted in #249, [acceptance tests for this one are failing](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/249#issuecomment-445449811) against kubernetes clusters [where the feature is not available and enabled](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/249#issuecomment-445451240), such as GKE 1.12.

**Comment by pdecat** [comment]
They do pass on minikube with kubernetes 1.14.1:

```
# make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetes\(Pod\|ReplicationController\|Deployment\|DaemonSet\|StatefulSet\).* -count=1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetes\(Pod\|ReplicationController\|Deployment\|DaemonSet\|StatefulSet\).* -count=1 -timeout 120m
=== RUN   TestAccKubernetesDaemonSet_minimal
--- PASS: TestAccKubernetesDaemonSet_minimal (3.33s)
=== RUN   TestAccKubernetesDaemonSet_basic
--- PASS: TestAccKubernetesDaemonSet_basic (5.54s)
=== RUN   TestAccKubernetesDaemonSet_importBasic
--- PASS: TestAccKubernetesDaemonSet_importBasic (2.82s)
=== RUN   TestAccKubernetesDaemonSet_with_template_metadata
--- PASS: TestAccKubernetesDaemonSet_with_template_metadata (5.20s)
=== RUN   TestAccKubernetesDaemonSet_initContainer
--- PASS: TestAccKubernetesDaemonSet_initContainer (2.84s)
=== RUN   TestAccKubernetesDaemonSet_noTopLevelLabels
--- PASS: TestAccKubernetesDaemonSet_noTopLevelLabels (2.73s)
=== RUN   TestAccKubernetesDeployment_basic
--- PASS: TestAccKubernetesDeployment_basic (2.90s)
=== RUN   TestAccKubernetesDeployment_initContainer
--- PASS: TestAccKubernetesDeployment_initContainer (2.96s)
=== RUN   TestAccKubernetesDeployment_importBasic
--- PASS: TestAccKubernetesDeployment_importBasic (3.06s)
=== RUN   TestAccKubernetesDeployment_generatedName
--- PASS: TestAccKubernetesDeployment_generatedName (2.71s)
=== RUN   TestAccKubernetesDeployment_importGeneratedName
--- PASS: TestAccKubernetesDeployment_importGeneratedName (2.74s)
=== RUN   TestAccKubernetesDeployment_with_security_context
--- PASS: TestAccKubernetesDeployment_with_security_context (2.88s)
=== RUN   TestAccKubernetesDeployment_with_container_liveness_probe_using_exec
--- PASS: TestAccKubernetesDeployment_with_container_liveness_probe_using_exec (2.80s)
=== RUN   TestAccKubernetesDeployment_with_container_liveness_probe_using_http_get
--- PASS: TestAccKubernetesDeployment_with_container_liveness_probe_using_http_get (2.83s)
=== RUN   TestAccKubernetesDeployment_with_container_liveness_probe_using_tcp
--- PASS: TestAccKubernetesDeployment_with_container_liveness_probe_using_tcp (2.92s)
=== RUN   TestAccKubernetesDeployment_with_container_lifecycle
--- PASS: TestAccKubernetesDeployment_with_container_lifecycle (2.85s)
=== RUN   TestAccKubernetesDeployment_with_container_security_context
--- PASS: TestAccKubernetesDeployment_with_container_security_context (2.75s)
=== RUN   TestAccKubernetesDeployment_with_volume_mount
--- PASS: TestAccKubernetesDeployment_with_volume_mount (2.74s)
=== RUN   TestAccKubernetesDeployment_with_resource_requirements
--- PASS: TestAccKubernetesDeployment_with_resource_requirements (2.57s)
=== RUN   TestAccKubernetesDeployment_with_empty_dir_volume
--- PASS: TestAccKubernetesDeployment_with_empty_dir_volume (2.66s)
=== RUN   TestAccKubernetesDeploymentUpdate_basic
--- PASS: TestAccKubernetesDeploymentUpdate_basic (4.85s)
=== RUN   TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate (2.61s)
=== RUN   TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_30perc_max_unavailable_40perc
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_30perc_max_unavailable_40perc (2.61s)
=== RUN   TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_1_max_unavailable_2
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_1_max_unavailable_2 (2.59s)
=== RUN   TestAccKubernetesDeployment_with_deployment_strategy_recreate
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_recreate (2.70s)
=== RUN   TestAccKubernetesDeployment_with_host_aliases
--- PASS: TestAccKubernetesDeployment_with_host_aliases (2.77s)
=== RUN   TestAccKubernetesPod_basic
--- PASS: TestAccKubernetesPod_basic (160.16s)
=== RUN   TestAccKubernetesPod_initContainer_updateForcesNew
--- PASS: TestAccKubernetesPod_initContainer_updateForcesNew (78.22s)
=== RUN   TestAccKubernetesPod_updateArgsForceNew
--- PASS: TestAccKubernetesPod_updateArgsForceNew (92.19s)
=== RUN   TestAccKubernetesPod_updateEnvForceNew
--- PASS: TestAccKubernetesPod_updateEnvForceNew (14.91s)
=== RUN   TestAccKubernetesPod_importBasic
--- PASS: TestAccKubernetesPod_importBasic (19.59s)
=== RUN   TestAccKubernetesPod_with_pod_security_context
--- PASS: TestAccKubernetesPod_with_pod_security_context (19.49s)
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_exec
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_exec (39.51s)
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_http_get
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_http_get (19.46s)
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_tcp
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_tcp (19.49s)
=== RUN   TestAccKubernetesPod_with_container_lifecycle
--- PASS: TestAccKubernetesPod_with_container_lifecycle (7.47s)
=== RUN   TestAccKubernetesPod_with_container_security_context
--- PASS: TestAccKubernetesPod_with_container_security_context (19.49s)
=== RUN   TestAccKubernetesPod_with_volume_mount
--- PASS: TestAccKubernetesPod_with_volume_mount (9.98s)
=== RUN   TestAccKubernetesPod_with_cfg_map_volume_mount
--- PASS: TestAccKubernetesPod_with_cfg_map_volume_mount (11.61s)
=== RUN   TestAccKubernetesPod_with_resource_requirements
--- PASS: TestAccKubernetesPod_with_resource_requirements (19.50s)
=== RUN   TestAccKubernetesPod_with_empty_dir_volume
--- PASS: TestAccKubernetesPod_with_empty_dir_volume (5.93s)
=== RUN   TestAccKubernetesPod_with_secret_vol_items
--- PASS: TestAccKubernetesPod_with_secret_vol_items (7.57s)
=== RUN   TestAccKubernetesPod_gke_with_nodeSelector
--- SKIP: TestAccKubernetesPod_gke_with_nodeSelector (0.01s)
    provider_test.go:223: The Kubernetes endpoint must come from GKE for this test to run - skipping
=== RUN   TestAccKubernetesReplicationController_deprecated_basic
--- PASS: TestAccKubernetesReplicationController_deprecated_basic (118.48s)
=== RUN   TestAccKubernetesReplicationController_deprecated_initContainer
--- PASS: TestAccKubernetesReplicationController_deprecated_initContainer (114.94s)
=== RUN   TestAccKubernetesReplicationController_deprecated_importBasic
--- PASS: TestAccKubernetesReplicationController_deprecated_importBasic (114.86s)
=== RUN   TestAccKubernetesReplicationController_deprecated_generatedName
--- PASS: TestAccKubernetesReplicationController_deprecated_generatedName (4.63s)
=== RUN   TestAccKubernetesReplicationController_deprecated_importGeneratedName
--- PASS: TestAccKubernetesReplicationController_deprecated_importGeneratedName (4.57s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_security_context
--- PASS: TestAccKubernetesReplicationController_deprecated_with_security_context (4.59s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_container_liveness_probe_using_exec
--- PASS: TestAccKubernetesReplicationController_deprecated_with_container_liveness_probe_using_exec (4.63s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_container_liveness_probe_using_http_get
--- PASS: TestAccKubernetesReplicationController_deprecated_with_container_liveness_probe_using_http_get (4.58s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_container_liveness_probe_using_tcp
--- PASS: TestAccKubernetesReplicationController_deprecated_with_container_liveness_probe_using_tcp (4.63s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_container_lifecycle
--- PASS: TestAccKubernetesReplicationController_deprecated_with_container_lifecycle (4.66s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_container_security_context
--- PASS: TestAccKubernetesReplicationController_deprecated_with_container_security_context (4.58s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_volume_mount
--- PASS: TestAccKubernetesReplicationController_deprecated_with_volume_mount (4.65s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_resource_requirements
--- PASS: TestAccKubernetesReplicationController_deprecated_with_resource_requirements (4.71s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_empty_dir_volume
--- PASS: TestAccKubernetesReplicationController_deprecated_with_empty_dir_volume (4.66s)
=== RUN   TestAccKubernetesReplicationController_basic
--- PASS: TestAccKubernetesReplicationController_basic (118.55s)
=== RUN   TestAccKubernetesReplicationController_initContainer
--- PASS: TestAccKubernetesReplicationController_initContainer (114.96s)
=== RUN   TestAccKubernetesReplicationController_importBasic
--- PASS: TestAccKubernetesReplicationController_importBasic (116.13s)
=== RUN   TestAccKubernetesReplicationController_generatedName
--- PASS: TestAccKubernetesReplicationController_generatedName (4.65s)
=== RUN   TestAccKubernetesReplicationController_importGeneratedName
--- PASS: TestAccKubernetesReplicationController_importGeneratedName (4.65s)
=== RUN   TestAccKubernetesReplicationController_with_security_context
--- PASS: TestAccKubernetesReplicationController_with_security_context (4.68s)
=== RUN   TestAccKubernetesReplicationController_with_container_liveness_probe_using_exec
--- PASS: TestAccKubernetesReplicationController_with_container_liveness_probe_using_exec (4.73s)
=== RUN   TestAccKubernetesReplicationController_with_container_liveness_probe_using_http_get
--- PASS: TestAccKubernetesReplicationController_with_container_liveness_probe_using_http_get (4.64s)
=== RUN   TestAccKubernetesReplicationController_with_container_liveness_probe_using_tcp
--- PASS: TestAccKubernetesReplicationController_with_container_liveness_probe_using_tcp (4.66s)
=== RUN   TestAccKubernetesReplicationController_with_container_lifecycle
--- PASS: TestAccKubernetesReplicationController_with_container_lifecycle (4.70s)
=== RUN   TestAccKubernetesReplicationController_with_container_security_context
--- PASS: TestAccKubernetesReplicationController_with_container_security_context (4.68s)
=== RUN   TestAccKubernetesReplicationController_with_volume_mount
--- PASS: TestAccKubernetesReplicationController_with_volume_mount (4.79s)
=== RUN   TestAccKubernetesReplicationController_with_resource_requirements
--- PASS: TestAccKubernetesReplicationController_with_resource_requirements (4.74s)
=== RUN   TestAccKubernetesReplicationController_with_empty_dir_volume
--- PASS: TestAccKubernetesReplicationController_with_empty_dir_volume (4.76s)
=== RUN   TestAccKubernetesStatefulSet_basic
--- PASS: TestAccKubernetesStatefulSet_basic (2.68s)
=== RUN   TestAccKubernetesStatefulSet_basic_idempotency
--- PASS: TestAccKubernetesStatefulSet_basic_idempotency (3.98s)
=== RUN   TestAccKubernetesStatefulSet_update_image
--- PASS: TestAccKubernetesStatefulSet_update_image (4.97s)
=== RUN   TestAccKubernetesStatefulSet_update_template_selector_labels
--- PASS: TestAccKubernetesStatefulSet_update_template_selector_labels (5.27s)
=== RUN   TestAccKubernetesStatefulSet_update_replicas
--- PASS: TestAccKubernetesStatefulSet_update_replicas (4.92s)
=== RUN   TestAccKubernetesStatefulSet_update_rolling_update_partition
--- PASS: TestAccKubernetesStatefulSet_update_rolling_update_partition (5.04s)
=== RUN   TestAccKubernetesStatefulSet_update_update_strategy_on_delete
--- PASS: TestAccKubernetesStatefulSet_update_update_strategy_on_delete (4.98s)
=== RUN   TestAccKubernetesStatefulSet_update_update_strategy_rolling_update
--- PASS: TestAccKubernetesStatefulSet_update_update_strategy_rolling_update (4.96s)
=== RUN   TestAccKubernetesStatefulSet_update_pod_template
--- PASS: TestAccKubernetesStatefulSet_update_pod_template (4.99s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 1466.897s
```

Not sure how to move this forward, maybe with a DiffSuppressFunc taking the availability of the feature and/or version of the cluster into account.

**Comment by jhoblitt** [comment]
I know that gke "alpha clusters" with more feature gates enabled can be created with `gcloud` -- it looks like the google provider has this functionality but I've never personally used it:

https://www.terraform.io/docs/providers/google/r/container_cluster.html#enable_kubernetes_alpha

**Comment by jhoblitt** [comment]
I don't know if it is possible to directly inspect feature gates via the api.  The only way know of to check them is via `kubectl cluster-info dump` and looking at the `kubelet` flags.

**Comment by pdecat** [comment]
If `kubectl cluster-info dump` can do it, it's exposed by the apiserver so this could be an option to detect the feature availability.

@alexsomesan did you have something similar in mind when you created https://github.com/terraform-providers/terraform-provider-kubernetes/pull/378?

**Comment by jhoblitt** [comment]
@pdecat yes but its just a a string with the cli command.

**Comment by pdecat** [comment]
Indeed:

```
# kubectl get pod -n kube-system kube-proxy-gke-tf-acc-test-2d0d814e-default-pool-99f381e6-jz8s -o yaml | grep feature-gates
      --feature-gates=DynamicKubeletConfig=false,RotateKubeletServerCertificate=true,ExperimentalCriticalPodAnnotation=true
```

It may be acceptable to rely on that just for the acceptance tests.

For real world setups, it could be left up to the user to know the limitations of its target cluster.

**Comment by pdecat** [comment]
@alexsomesan yeah, that's what we were discussing above.

Checking the kubernetes cluster version in acceptance tests could be enough and is certainly the easiest as I don't believe the provider targets non standard configurations with alpha features.

**Comment by pdecat** [comment]
And what about implementing a `DiffSuppressFunc` for the `run_as_group` field like [what's done for persistent volumes](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/v1.6.2/kubernetes/resource_kubernetes_persistent_volume.go#L38)?

Note: the only other place where server version is checked is for [services updates](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/188074bb842e0d708c3a95e095c555cd4fec5e03/kubernetes/structure_service_spec.go#L187).

**Comment by pdecat** [comment]
I've implemented the acceptance tests skipping option.

With minikube 1.0.0 and kubernetes 1.14.1:

```
# make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetes.*security_context.* -count=1'                                                                                        
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetes.*security_context.* -count=1 -timeout 120m                                                                                      
=== RUN   TestAccKubernetesDeployment_with_security_context
--- PASS: TestAccKubernetesDeployment_with_security_context (3.19s)
=== RUN   TestAccKubernetesDeployment_with_security_context_run_as_group
--- PASS: TestAccKubernetesDeployment_with_security_context_run_as_group (2.94s)
=== RUN   TestAccKubernetesDeployment_with_container_security_context
--- PASS: TestAccKubernetesDeployment_with_container_security_context (2.91s)
=== RUN   TestAccKubernetesDeployment_with_container_security_context_run_as_group
--- PASS: TestAccKubernetesDeployment_with_container_security_context_run_as_group (2.90s)
=== RUN   TestAccKubernetesPod_with_pod_security_context
--- PASS: TestAccKubernetesPod_with_pod_security_context (5.84s)
=== RUN   TestAccKubernetesPod_with_pod_security_context_run_as_group
--- PASS: TestAccKubernetesPod_with_pod_security_context_run_as_group (3.90s)
=== RUN   TestAccKubernetesPod_with_container_security_context
--- PASS: TestAccKubernetesPod_with_container_security_context (3.85s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_security_context
--- PASS: TestAccKubernetesReplicationController_deprecated_with_security_context (4.79s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_container_security_context
--- PASS: TestAccKubernetesReplicationController_deprecated_with_container_security_context (4.79s)                                                                                     
=== RUN   TestAccKubernetesReplicationController_with_security_context
--- PASS: TestAccKubernetesReplicationController_with_security_context (4.96s)
=== RUN   TestAccKubernetesReplicationController_with_security_context_run_as_group
--- PASS: TestAccKubernetesReplicationController_with_security_context_run_as_group (4.93s)
=== RUN   TestAccKubernetesReplicationController_with_container_security_context
--- PASS: TestAccKubernetesReplicationController_with_container_security_context (4.84s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 49.884s
```

With GKE 1.12.7-gke.7:

```
# make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetes.*security_context.* -count=1'                                                                                        
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetes.*security_context.* -count=1 -timeout 120m                                                                                      
=== RUN   TestAccKubernetesDeployment_with_security_context
--- PASS: TestAccKubernetesDeployment_with_security_context (6.44s)
=== RUN   TestAccKubernetesDeployment_with_security_context_run_as_group
--- SKIP: TestAccKubernetesDeployment_with_security_context_run_as_group (0.11s)
    provider_test.go:246: The Kubernetes version must be 1.14.0 or newer for this test to run - skipping                                                                                
=== RUN   TestAccKubernetesDeployment_with_container_security_context
--- PASS: TestAccKubernetesDeployment_with_container_security_context (5.89s)
=== RUN   TestAccKubernetesDeployment_with_container_security_context_run_as_group
--- SKIP: TestAccKubernetesDeployment_with_container_security_context_run_as_group (0.11s)
    provider_test.go:246: The Kubernetes version must be 1.14.0 or newer for this test to run - skipping                                                                                
=== RUN   TestAccKubernetesPod_with_pod_security_context
--- PASS: TestAccKubernetesPod_with_pod_security_context (11.88s)
=== RUN   TestAccKubernetesPod_with_pod_security_context_run_as_group
--- SKIP: TestAccKubernetesPod_with_pod_security_context_run_as_group (0.11s)
    provider_test.go:246: The Kubernetes version must be 1.14.0 or newer for this test to run - skipping                                                                                
=== RUN   TestAccKubernetesPod_with_container_security_context
--- PASS: TestAccKubernetesPod_with_container_security_context (6.90s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_security_context
--- PASS: TestAccKubernetesReplicationController_deprecated_with_security_context (5.31s)
=== RUN   TestAccKubernetesReplicationController_deprecated_with_container_security_context
--- PASS: TestAccKubernetesReplicationController_deprecated_with_container_security_context (5.24s)                                                                                     
=== RUN   TestAccKubernetesReplicationController_with_security_context
--- PASS: TestAccKubernetesReplicationController_with_security_context (5.21s)
=== RUN   TestAccKubernetesReplicationController_with_security_context_run_as_group
--- SKIP: TestAccKubernetesReplicationController_with_security_context_run_as_group (0.12s)
    provider_test.go:246: The Kubernetes version must be 1.14.0 or newer for this test to run - skipping                                                                                
=== RUN   TestAccKubernetesReplicationController_with_container_security_context
--- PASS: TestAccKubernetesReplicationController_with_container_security_context (5.26s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 52.638s
```

**Comment by jhoblitt** [comment]
This is a much better approach!  I've discovered that some clusters don't use `--feature-gates` at all (pure defaults), so the only way to determine features sets in a lot of cases would be a version lookup table.

**Comment by pdecat** [comment]
> Do you mean to filter out user-provided values of run_as_group when the server doesn't support it?

Yeah, that's what it would have resulted in. Bad idea IMO.

**Comment by alexsomesan** [comment]
yeah, I think we're safer like this, given that we don't have a deterministic way of telling whether the feature is on or not.
I'll merge this and let's see how it behaves with users.

**Pull request merged**
