### PR TITLE
Bugfix: host_alias to host_aliases

### PR DESCRIPTION
**Pull request by minac**
Bugfix: host_alias to host_aliases

### CODE REVIEW

**Comment by pdecat** [comment]
There are other places in docs with the same issue, e.g. https://github.com/terraform-providers/terraform-provider-kubernetes/blame/master/website/docs/r/daemonset.html.markdown#L127

**Comment by pdecat** [comment]
In order to lighten the documentation maintenance burden, I believe we should remove the duplicated pod spec documentation from the [`kubernetes_daemon_set`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/daemonset.html.markdown#template) and [`kubernetes_deployment`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/deployment.html.markdown#template) resources and just refer to the [`kubernetes_pod` documentation](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/pod.html.markdown#spec-1), similar to what's done for [`kubernetes_replication_controller`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/replication_controller.html.markdown#nested-blocks-3) and [`kubernetes_stateful_set`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/stateful_set.html.markdown#spectemplatespec).

@alexsomesan WDYT?

Notes:
- in the case of [`kubernetes_daemon_set`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/fbf2bd5cb8c94022ae2ef07b1ec720e081ce9e1e/kubernetes/resource_kubernetes_daemonset.go#L109) and [`kubernetes_stateful_set`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/fbf2bd5cb8c94022ae2ef07b1ec720e081ce9e1e/kubernetes/schema_stateful_set_spec.go#L58) resources, the whole `template` block comes from the `pod` schema using the `podTemplateFields()` function which relies on the `namespacedMetadataSchema()` and `podSpecFields()` functions.
-  in the case of [`kubernetes_deployment`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/ee47b93c035892aad33ddfc7464caad3889d3654/kubernetes/resource_kubernetes_deployment.go#L184), only `spec.template.spec` comes directly from the `pod` schema using the `podSpecFields()` function, the `spec.template.metadata` comes from `metadataSchema()` (not `namespacedMetadataSchema()`).
- in the case of [`kubernetes_replication_controller`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/d5ff12c5b137b7a04be60e640d3c7c8b654d659e/kubernetes/resource_kubernetes_replication_controller.go#L66), the whole `template` block comes from the `pod` schema using the `replicationControllerTemplateFieldSpec()` function which relies on the `namespacedMetadataSchema()` and `podSpecFields()` functions and implements support for legacy fields which were misplaced (see #193).

Some refactoring there could help improve the situation further.

**Comment by minac** [comment]
Although I completely agree with the comments, aren't we making the scope of this simple PR way too big? Maybe a separate issue would be better to make improvements/fixes in other locations?
I know I wasted hours of my day because of this one bug and can imagine others are suffering from the same problem.

**Comment by pdecat** [comment]
Agreed. Maybe just address https://github.com/terraform-providers/terraform-provider-kubernetes/pull/413#issuecomment-485975104 here.
We'll take care of the rest in another issue/PR.

**Comment by pdecat** [comment]
Sorry about the trouble by the way, I'm responsible for the typo when I added the documentation that I noticed was missing from https://github.com/terraform-providers/terraform-provider-kubernetes/pull/367/files

**Comment by minac** [comment]
Hey @pdecat, we're all humans here! Let's just get this fixed using the magic of open source docs :)

**Comment by alexsomesan** [comment]
> In order to lighten the documentation maintenance burden, I believe we should remove the duplicated pod spec documentation from the [`kubernetes_daemon_set`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/daemonset.html.markdown#template) and [`kubernetes_deployment`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/deployment.html.markdown#template) resources and just refer to the [`kubernetes_pod` documentation](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/pod.html.markdown#spec-1), similar to what's done for [`kubernetes_replication_controller`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/replication_controller.html.markdown#nested-blocks-3) and [`kubernetes_stateful_set`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/website/docs/r/stateful_set.html.markdown#spectemplatespec).
> 
> @alexsomesan WDYT?
> 
> Notes:
> 
> * in the case of [`kubernetes_daemon_set`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/fbf2bd5cb8c94022ae2ef07b1ec720e081ce9e1e/kubernetes/resource_kubernetes_daemonset.go#L109) and [`kubernetes_stateful_set`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/fbf2bd5cb8c94022ae2ef07b1ec720e081ce9e1e/kubernetes/schema_stateful_set_spec.go#L58) resources, the whole `template` block comes from the `pod` schema using the `podTemplateFields()` function which relies on the `namespacedMetadataSchema()` and `podSpecFields()` functions.
> * in the case of [`kubernetes_deployment`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/ee47b93c035892aad33ddfc7464caad3889d3654/kubernetes/resource_kubernetes_deployment.go#L184), only `spec.template.spec` comes directly from the `pod` schema using the `podSpecFields()` function, the `spec.template.metadata` comes from `metadataSchema()` (not `namespacedMetadataSchema()`).
> * in the case of [`kubernetes_replication_controller`](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/d5ff12c5b137b7a04be60e640d3c7c8b654d659e/kubernetes/resource_kubernetes_replication_controller.go#L66), the whole `template` block comes from the `pod` schema using the `replicationControllerTemplateFieldSpec()` function which relies on the `namespacedMetadataSchema()` and `podSpecFields()` functions and implements support for legacy fields which were misplaced (see #193).
> 
> Some refactoring there could help improve the situation further.

Patrick, I agree. We should unify the pod templates across all workload resources and make everything re-usable. I would love that.
However the provider is still missing features and entire resources, so priority has to go to that on my side until we have decent coverage.

Happy to look at PRs though 🤓

**Comment by aareet** [comment]
Closing in favour of #869 which fixes the issue in the daemonset & pod docs as well. I retained the original commit and author from this PR.

**Pull request closed without merging**
