### PR TITLE
resource/kubernetes_persistent_volume: Add support for storage_class_name

### PR DESCRIPTION
**Pull request by sergei-ivanov**
It is basically a partial rebase of #72 plus a few additional fixes to make it actually work.

I have tested it against minikube by creating PVs with the source `host_path`, which is the simplest setup I could produce locally without hitting the cloud.

The testing revealed that creating a PV _without_ a storage class and then amending it to the one _with_ a storage class did not work because Kubernetes sent back a JSON without `/spec/storageClassName` path in it. That resulted in:
```
Error: Error applying plan:
1 error(s) occurred:
* kubernetes_persistent_volume.example: 1 error(s) occurred:
* kubernetes_persistent_volume.example: jsonpatch replace operation does not apply: doc is missing key: /spec/storageClassName
```

I had to tweak `patchPersistentVolumeSpec` a bit to produce either `add` or `replace` operation, which worked a treat in the end: I could add, change or remove storage class in the terraform manifest, and kubernetes applied the changes to the persistent volume.
I am not very experienced in Go, and there may be a more elegant way of doing what I've done,
so please feel free to correct me here.

Closes #72

### CODE REVIEW

**Comment by sergei-ivanov** [comment]
This should partially address #74.
To fully address it, I think I'll need to roll another PR that will allow specifying empty storage class on PVC (there is a difference in binding behaviour between specifying an empty storage class and specifying no storage class at all).

**Comment by sergei-ivanov** [comment]
I had a go at trying to allow empty or null storage class name for persistent volume _claims_, but that was thwarted by the fact that `storage_class_name` is marked as a _computed_ attribute in the Terraform schema for PVCs. Which means, there is no way to change from a specific storage class to default or empty storage class. I guess it has to stay that way, because the only other option is to query for a storage class that has `storageclass.kubernetes.io/is-default-class: true` and use that to suppress diffs.

**Comment by fromz** [comment]
This patch worked perfectly for me, thanks!

**Comment by sergei-ivanov** [comment]
@radeksimko , thank you for looking after the tests. I did not have a spare GCP project to run them against, so I did not dare touch them. I ran a lot of manual checks against my local minikube though. Everything looks great, thank you for accepting the PR, we are looking forward to it being rolled into the next release of the provider!

**Comment by fromz** [comment]
Thanks guys!

**Comment by coderfi** [comment]
Thanks for picking up the work, @sergei!

**Pull request merged**
