### PR TITLE
Upgrade k8s client libs to 1.10

### PR DESCRIPTION
**Pull request by cosmopetrich**
This is based on the work of @nickschuch and @pdecat in #117. Access to a newer Kube client will help unblock several open PRs that add useful features (ClusterRoleBinging, Deployments, NetworkPolicies) and I thought it might be easier to open a new PR against Kube 1.10 and a newer `master` than to just ping the existing PR. I'm happy to close this if we'd rather proceed with the original PR.

The steps used to create this are almost identical to those used for the 1.9 PR. I also had to update github.com/Azure/go-autorest.

The tests and basic acceptance tests pass. I believe that the acceptance test failure in the 1.9 PR was fixed by #122.

### CODE REVIEW

**Comment by evilmarty** [comment]
To help expedite this it's probably a good idea to post test results.

**Comment by christopherhein** [comment]
Anything that is needed to help move this along, would be nice to see EKS support for the Kubernetes TF provider :)

**Comment by v00d00** [comment]
Offering my help to get this merged also? Are we waiting on something specific?

**Comment by cosmopetrich** [comment]
@christopherhein @v00d00 My impression is that this provider is unmaintained at the moment. I'm not sure if there is a way to move the open PRs along until a maintainer is found (see #178).

Until then it might be worth taking a look at the actively-maintained fork https://github.com/sl1pm4t/terraform-provider-kubernetes which includes some additional features such as RBAC and Deployments.

**Comment by christopherhein** [comment]
Thank you @cosmopetrich ! Very helpful!

**Comment by Jeeppler** [comment]
I am unable to use this provider without support for v1.10. This the only version supported by EKS.

**Comment by alexsomesan** [comment]
I've retested this change and it works as expected on top of current master.
I think it's safe to merge.

**Comment by alexsomesan** [comment]
@Jeeppler I'm thinking this change alone doesn't bring a whole lot of value to users - it mostly helps developers. Is this blocking you in any way?
I'd like to wait for https://github.com/terraform-providers/terraform-provider-kubernetes/pull/73 to get merged and then release.

**Comment by Jeeppler** [comment]
@alexsomesan Yes, I work with EKS which uses Kubernetes 1.10, basically I cant use the Kubernetes provider unless I can use it with Kubernetes 1.10.

**Comment by alexsomesan** [comment]
@Jeeppler As far as I could test, it seems the current release of the provider can talk to an EKS cluster just fine. Would you be so kind to provide me with more details of how exactly is it blocking you?

This particular change won't actually give you access to any new 1.10 features unless the specific resources are added or updated explicitly in the K8S provider.

**Comment by coryflucas** [comment]
@alexsomesan I believe this change should allow using a kube config with the aws-iam-authenticator which is used via an ExecCredentials resource in the config. See: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins.

**Comment by coryflucas** [comment]
Also see https://github.com/terraform-providers/terraform-provider-kubernetes/issues/161.

**Pull request merged**
