### PR TITLE
add optional secret_key_ref

### PR DESCRIPTION
**Pull request by karlhungus**
#### What this does

1. Add [`optional`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#secretkeyselector-v1-core) for secret_key_ref
~~1. Add [`divisor`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#resourcefieldselector-v1-core) field for resource_field_ref~~

Fix: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/240

### CODE REVIEW

**Comment by karlhungus** [comment]
(I didn't actually need divisor, but i thought while i was in there...)

**Comment by alexsomesan** [comment]
Thanks for contributing this fix!

There is a bit more to be done for this change to be functional and complete. You must also add these new attributes to the relevant expander / flattener functions. The role of these functions is to translate the attribute values between Terraform's internal representation and the Kubernetes client's own representation.

More specifically, the attribute `optional` must be handled in the functions `expandSecretKeyRef` and `flattenSecretKeyRef`.
The same way, the attribute `divisor` must be handled in both `flattenResourceFieldSelector` and `expandResourceFieldRef`.

Have a look at how existing attributes are processed to get a sense what is adequate for these new ones.

**Comment by karlhungus** [comment]
@alexsomesan Hey, I intended to test this locally; and admit i should have known better having spent tie on  https://github.com/terraform-providers/terraform-provider-kubernetes/pull/294, I'll re-ping when this is ready

**Comment by karlhungus** [comment]
@alexsomesan All right, this looks to pass on my acceptance tests. I removed the divisor bit because it looked bigger and I don't personally need it yet.

**Pull request closed without merging**
