### PR TITLE
Add support for envFrom on container definitions

### PR DESCRIPTION
**Pull request by pdecat**
Relates to #78.

- [x] Rebase on master
- [x] Update schema
- [x] Update documentation
- [x] Implement mapping
- [x] Add acceptance test cases

### CODE REVIEW

**Comment by pdecat** [comment]
# Test results

```
# make testacc TEST=./kubernetes/ TESTARGS='-run=TestAccKubernetesPod_basic'                                     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes/ -v -run=TestAccKubernetesPod_basic -timeout 120m
=== RUN   TestAccKubernetesPod_basic
--- PASS: TestAccKubernetesPod_basic (9.39s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 9.601s
```

**Comment by ayansen** [comment]
is there a timeline as to when this card is going to get merged ?

**Comment by rawkode** [comment]
Is there anything blocking this from being merged?

**Comment by seivan** [comment]
Does this mean I can define ConfigMap from Terraform output values (e.g creating Route53 subdomains and RDS resources) while still defining the rest of the infrastructure in regular YAML manifest files? 
I don't want to use the K8 provider fully, but just for defining configmaps

**Comment by nblakely731** [comment]
Any timeline around when this will be merged?  Looks like everything is passing unit tests.

**Comment by pdecat** [comment]
# Acceptance tests results

New run after rebase with local minikube 0.29:

```
make testacc TEST=./kubernetes/ TESTARGS='-run=TestAccKubernetesPod_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes/ -v -run=TestAccKubernetesPod_ -timeout 120m
=== RUN   TestAccKubernetesPod_basic
--- PASS: TestAccKubernetesPod_basic (108.69s)
=== RUN   TestAccKubernetesPod_initContainer_updateForcesNew
--- PASS: TestAccKubernetesPod_initContainer_updateForcesNew (186.64s)
=== RUN   TestAccKubernetesPod_updateArgsForceNew
--- PASS: TestAccKubernetesPod_updateArgsForceNew (100.54s)
=== RUN   TestAccKubernetesPod_updateEnvForceNew
--- PASS: TestAccKubernetesPod_updateEnvForceNew (67.37s)
=== RUN   TestAccKubernetesPod_importBasic
--- PASS: TestAccKubernetesPod_importBasic (68.72s)
=== RUN   TestAccKubernetesPod_with_pod_security_context
--- PASS: TestAccKubernetesPod_with_pod_security_context (5.05s)
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_exec
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_exec (51.89s)
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_http_get
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_http_get (9.87s)
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_tcp
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_tcp (18.67s)
=== RUN   TestAccKubernetesPod_with_container_lifecycle
--- PASS: TestAccKubernetesPod_with_container_lifecycle (18.68s)
=== RUN   TestAccKubernetesPod_with_container_security_context
--- PASS: TestAccKubernetesPod_with_container_security_context (18.69s)
=== RUN   TestAccKubernetesPod_with_volume_mount
--- PASS: TestAccKubernetesPod_with_volume_mount (17.14s)
=== RUN   TestAccKubernetesPod_with_cfg_map_volume_mount
--- PASS: TestAccKubernetesPod_with_cfg_map_volume_mount (5.14s)
=== RUN   TestAccKubernetesPod_with_resource_requirements
--- PASS: TestAccKubernetesPod_with_resource_requirements (6.67s)
=== RUN   TestAccKubernetesPod_with_empty_dir_volume
--- PASS: TestAccKubernetesPod_with_empty_dir_volume (18.70s)
=== RUN   TestAccKubernetesPod_with_secret_vol_items
--- PASS: TestAccKubernetesPod_with_secret_vol_items (6.73s)
=== RUN   TestAccKubernetesPod_gke_with_nodeSelector
--- SKIP: TestAccKubernetesPod_gke_with_nodeSelector (0.01s)
        provider_test.go:215: The Kubernetes endpoint must come from GKE for this test to run - skipping
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 709.256s
```

**Comment by pdecat** [comment]
Hi @alexsomesan, would you mind having a look at this one?

**Pull request merged**
