### PR TITLE
Wait for deployment rollout status

### PR DESCRIPTION
**Pull request by enozero**
replicationcontrollers are not created for a deployment. So we need to
wait for the deployment itself to finish.

### CODE REVIEW

**Comment by enozero** [comment]
I'm still trying to get a test written on this, but here is the change so far.

**Comment by enozero** [comment]
@alexsomesan for visibility

**Comment by alexsomesan** [comment]
Looks good so far!
Let me know if you get around to writing that test. Otherwise I can also add one afterwards.
Thanks!

**Comment by enozero** [comment]
This is to resolve https://github.com/terraform-providers/terraform-provider-kubernetes/issues/210

**Comment by enozero** [comment]
Before (without fix):

```
C:\Users\Andy\Code\src\github.com\terraform-providers\terraform-provider-kubernetes\kubernetes [deployment-update-check-rollout-status +0 ~1 -0 | +0 ~2 -0 !]> & { $env:TF_ACC="1"; $env:KUBE_CTX_CLUSTER="docker-for-desktop-cluster"; $env:KUBE_CTX_AUTH_INFO="docker-for-desktop"; go test -v --run ^TestAccKubernetesDeploymentUpdate_basic$ }
# github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/terraform-providers/terraform-provider-aws/aws
..\vendor\github.com\terraform-providers\terraform-provider-aws\aws\resource_aws_kinesis_firehose_delivery_stream.go:1315:6: lastError declared but not used
vet: typecheck failures
=== RUN   TestAccKubernetesDeploymentUpdate_basic
--- FAIL: TestAccKubernetesDeploymentUpdate_basic (29.23s)
    testing.go:518: Step 1 error: Error applying: 1 error(s) occurred:

        * kubernetes_deployment.test: 1 error(s) occurred:

        * kubernetes_deployment.test: replicationcontrollers "tf-acc-test-8cu2mtm0ql" not found
FAIL
exit status 1
FAIL    github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 30.976s
```

After (with fix):
```
C:\Users\Andy\Code\src\github.com\terraform-providers\terraform-provider-kubernetes\kubernetes [deployment-update-check-rollout-status +0 ~1 -0 | +0 ~2 -0 !]> & { $env:TF_ACC="1"; $env:KUBE_CTX_CLUSTER="docker-for-desktop-cluster"; $env:KUBE_CTX_AUTH_INFO="docker-for-desktop"; go test -v --run ^TestAccKubernetesDeploymentUpdate_basic$ }
# github.com/terraform-providers/terraform-provider-kubernetes/vendor/github.com/terraform-providers/terraform-provider-aws/aws
..\vendor\github.com\terraform-providers\terraform-provider-aws\aws\resource_aws_kinesis_firehose_delivery_stream.go:1315:6: lastError declared but not used
vet: typecheck failures
=== RUN   TestAccKubernetesDeploymentUpdate_basic
--- PASS: TestAccKubernetesDeploymentUpdate_basic (13.65s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 14.942s
```

**Comment by jeff1985** [comment]
Hi @alexsomesan ,

this is still happening to me. Very annoying... Can you give an ETA for 1.4.0 release?

**Comment by alexsomesan** [comment]
@jeff1985 I'm planning to cut 1.4.0 as soon as we merge the StatefulSet PR (https://github.com/terraform-providers/terraform-provider-kubernetes/pull/203)

**Pull request merged**
