### PR TITLE
Support priorityClassName in PodSpec.

### LINKED ISSUE #506: Support `priorityClassName` for pods (deployments, daemonset, etc)
1.14 made the pod priority feature stable, so the provider should be updated to expose this functionality.

This will require updating the Kubernetes API library to 1.14 from 1.11.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#podspec-v1-core

### PR DESCRIPTION
**Pull request by dsymonds**
This adds support for this field in PodSpec, part of Deployments,
StatefulSets, CronJobs and anything else that embeds a PodSpec.

The PriorityClass resource was added in #495.

Fixes #506.

### CODE REVIEW

**Comment by dsymonds** [comment]
Hey @alexsomesan, can we get this change in for the next release? It's the obvious complement to #495.

**Comment by alexsomesan** [comment]
Change looks ok. I'm testing it now.

**Comment by alexsomesan** [comment]
CI passes OK.

@dsymonds This new attribute should be mentioned in the docs. Mind adding it? Then we can merge.

**Comment by dsymonds** [comment]
Sure. Docs update.

**Comment by alexsomesan** [comment]
@dsymonds The attribute needs to be added to the docs in two other places (posSpecTemplate is shared by several resources). I tried pushing these changes to your branch but it seems I don't have permissions.

Here's where it needs to be added:
```
iff --git a/website/docs/r/daemonset.html.markdown b/website/docs/r/daemonset.html.markdown
index c5179b2c..3ac16f8d 100644
--- a/website/docs/r/daemonset.html.markdown
+++ b/website/docs/r/daemonset.html.markdown
@@ -153,6 +153,7 @@ For more info see [Kubernetes reference](http://kubernetes.io/docs/user-guide/an
 * `image_pull_secrets` - (Optional) ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets$
 * `node_name` - (Optional) NodeName is a request to schedule this pod onto a specific node. If it is non-empty, the scheduler simply schedules this pod onto that node, assuming that it fits resource require$
 * `node_selector` - (Optional) NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. For more info s$
+* `priority_class_name` - (Optional) If specified, indicates the pod's priority. 'system-node-critical' and 'system-cluster-critical' are two special keywords which indicate the highest priorities with the $
 * `restart_policy` - (Optional) Restart policy for all containers within the pod. One of Always, OnFailure, Never. For more info see [Kubernetes reference](http://kubernetes.io/docs/user-guide/pod-states#re$
 * `security_context` - (Optional) SecurityContext holds pod-level security attributes and common container settings. Optional: Defaults to empty
 * `service_account_name` - (Optional) ServiceAccountName is the name of the ServiceAccount to use to run this pod. For more info see http://releases.k8s.io/HEAD/docs/design/service_accounts.md.
diff --git a/website/docs/r/deployment.html.markdown b/website/docs/r/deployment.html.markdown
index 843aab81..52e315c6 100644
--- a/website/docs/r/deployment.html.markdown
+++ b/website/docs/r/deployment.html.markdown
@@ -158,6 +158,7 @@ For more info see [Kubernetes reference](http://kubernetes.io/docs/user-guide/an
 * `image_pull_secrets` - (Optional) ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets$
 * `node_name` - (Optional) NodeName is a request to schedule this pod onto a specific node. If it is non-empty, the scheduler simply schedules this pod onto that node, assuming that it fits resource require$
 * `node_selector` - (Optional) NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. For more info s$
+* `priority_class_name` - (Optional) If specified, indicates the pod's priority. 'system-node-critical' and 'system-cluster-critical' are two special keywords which indicate the highest priorities with the $
 * `restart_policy` - (Optional) Restart policy for all containers within the pod. One of Always, OnFailure, Never. For more info see [Kubernetes reference](http://kubernetes.io/docs/user-guide/pod-states#re$
 * `security_context` - (Optional) SecurityContext holds pod-level security attributes and common container settings. Optional: Defaults to empty
 * `service_account_name` - (Optional) ServiceAccountName is the name of the ServiceAccount to use to run this pod. For more info see http://releases.k8s.io/HEAD/docs/design/service_accounts.md.
```

**Comment by dsymonds** [comment]
Ah, right, sorry. I didn't realise it was duplicated all over the place. Might be nice for those docs to be auto-generated.

PTAL.

**Comment by tdmalone** [comment]
Thanks team! @alexsomesan do you have a target date for the next release?

**Pull request merged**
