### PR TITLE
Add support for kubernetes_api_service.spec.service.port

### LINKED ISSUE #660: kubernetes_api_service.spec.service.port  not supported
### Terraform Version
Terraform v0.12.9
+ provider.aws v2.30.0
+ provider.kubernetes v1.9.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)
- kubernetes_api_service.spec.service

### Expected Behavior
Service references support the optional port, per
https://godoc.org/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1#ServiceReference

### Actual Behavior
There is no `port` argument.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/487

### PR DESCRIPTION
**Pull request by pdecat**
This PR adds support for kubernetes_api_service.spec.service.port and resolves #660

### CODE REVIEW

**Comment by pdecat** [comment]
Acceptance tests results:

```
make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetesAPIService.* -count=1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetesAPIService.* -count=1 -timeout 120m
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.17.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.17.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-aws v2.32.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-aws v2.32.0+incompatible
=== RUN   TestAccKubernetesAPIService_basic
--- PASS: TestAccKubernetesAPIService_basic (1.50s)
=== RUN   TestAccKubernetesAPIService_importBasic
--- PASS: TestAccKubernetesAPIService_importBasic (0.65s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 2.195s
```

**Comment by pdecat** [comment]
Rebased on master.

**Comment by pdecat** [comment]
Rebased on master, no longer WIP.

Acceptance tests results:

```
# make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetesAPIService.* -count=1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetesAPIService.* -count=1 -timeout 120m
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.17.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.17.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-aws v2.32.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-aws v2.32.0+incompatible
=== RUN   TestAccKubernetesAPIService_basic
--- PASS: TestAccKubernetesAPIService_basic (1.64s)
=== RUN   TestAccKubernetesAPIService_importBasic
--- PASS: TestAccKubernetesAPIService_importBasic (0.79s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 2.478s
```

**Comment by tdmalone** [comment]
Hi again @pdecat (cc @alexsomesan),

Also just letting you know that after upgrading to v1.10.0 which includes this change, I'm getting continual spurious diffs as follows:

```
Terraform will perform the following actions:

  ~ module.eks.kubernetes_api_service.metrics_server
      spec.0.service.0.port: "0" => "443"

Plan: 0 to add, 1 to change, 0 to destroy.
```

After applying this change, the same diff is generated again.

Would you suggest the best way around this is just to set the `port` in the Terraform config to `0`?

Similar to https://github.com/terraform-providers/terraform-provider-kubernetes/pull/275#issuecomment-552342127, it's possible (although I'm not fully aware of the process) that this value might need to be computed if it already exists.

**Comment by pdecat** [comment]
Hi again @tdmalone :)

With the current implementation, setting `0` will be rejected because there's validation https://github.com/terraform-providers/terraform-provider-kubernetes/pull/665/files#diff-9cf6f542606fe051093b967a81103dd6R81 on the port number.

Please note that this change is less impacting than #275 and https://github.com/terraform-providers/terraform-provider-kubernetes/pull/552#issuecomment-551942469 because it does not requires workloads replacement.

**Comment by pdecat** [comment]
I'm going to try and test if making `port` computed would avoid those diffs without other side effects.

**Comment by tdmalone** [comment]
Thanks for the quick replies @pdecat! If 0 can't be set, what would you suggest doing in order to resolve the ongoing diffs from this change? If I set it to 443 in config I suspect that's the same as leaving the default in place, which is resulting in the diffs anyway.

Perhaps the provider isn't actually making the change? When describing my APIService object after applying the above, I don't see any `port` set:
```
...
Spec:
  Group:                     metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            metrics-server
    Namespace:       kube-system
  Version:           v1beta1
  Version Priority:  100
...
```

**Comment by pdecat** [comment]
Since v1.10.0 and #630, setting `TF_LOG=debug` should allow you to see what actually be sent to the kubernetes API.

You should see a PATCH request with service port 443 (https://github.com/terraform-providers/terraform-provider-kubernetes/blob/2bfe98978cb84655dc3080dac8602bad3fac27ae/kubernetes/resource_kubernetes_service.go#L271).

**Comment by pdecat** [comment]
Oh, `port` was introduced in kubernetes 1.15: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/237#issuecomment-547471585

What kubernetes version are you using?

**Comment by tdmalone** [comment]
Oh - that'd be it! I'm on version 1.13. EKS [doesn't even support](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html) 1.15 yet; we're looking at upgrading to 1.14 soon.

In that case... the question becomes: what version of Kubernetes does this provider support? My impression (though I just assumed this 😛) was that it generally does its best to support 'current' versions. In that case, this option should possibly be ignored on older versions?

In the meantime though until I upgrade to 1.15, I could just ignore_changes on `spec.0.service.0.port`.

**Comment by pdecat** [comment]
> In that case... the question becomes: what version of Kubernetes does this provider support?

Indeed.

Running acceptance tests against kubernetes 1.14.8 with minikube reveals the issue:

```
# make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetesAPIService.* -count=1'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetesAPIService.* -count=1 -timeout 120m
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding k8s.io/client-go v12.0.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.17.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-aws v2.32.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-google v2.17.0+incompatible
go: finding github.com/terraform-providers/terraform-provider-aws v2.32.0+incompatible
=== RUN   TestAccKubernetesAPIService_basic
--- FAIL: TestAccKubernetesAPIService_basic (0.40s)
    testing.go:635: Step 0 error: Check failed: 1 error occurred:
                * Check 11/17 error: kubernetes_api_service.test: Attribute 'spec.0.service.0.port' expected "443", got "0"


=== RUN   TestAccKubernetesAPIService_importBasic
--- FAIL: TestAccKubernetesAPIService_importBasic (0.46s)
    testing.go:635: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: kubernetes_api_service.test
[...]
          spec.0.service.0.port:                    "0" => "443"
[...]



        STATE:

        kubernetes_api_service.test:
[...]
          spec.0.service.0.port = 0
[...]
=== RUN   TestAccKubernetesAPIService_importServicePort
--- FAIL: TestAccKubernetesAPIService_importServicePort (0.40s)
    testing.go:635: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: kubernetes_api_service.test
[...]
          spec.0.service.0.port:                    "0" => "8443"
[...]

        STATE:

        kubernetes_api_service.test:
[...]
          spec.0.service.0.port = 0
[...]
FAIL
FAIL    github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 1.298s
FAIL
make: *** [GNUmakefile:17: testacc] Error 1
```

For fields introduced in new kubernetes versions, avoiding this kind of issues is possible by:
- making them computed and not specifying default value,
- having separate acceptance tests that are skipped based on kubernetes API version like was done for `run_as_group`: #414 https://github.com/terraform-providers/terraform-provider-kubernetes/pull/414#issuecomment-487158271

**Comment by alexsomesan** [comment]
@tdmalone That's a fair question and I should make the versions supported more clearly visible in the provider README.

As things stand right now, we have to align the supported Kubernetes versions with the versions that the currently vendored `k8s.io/client-go` package supports. These are well documented here: https://github.com/kubernetes/client-go#compatibility-matrix. We are currently using client-go v12.

That said, because of the static linking nature of Go and unless the client-go library doesn't move to a versioned package path (i.e. `k8s.io/client-go/v12`, etc.) there is no way of dynamically choosing supported versions at runtime in the provider (as we can only import the client through a single package path).

**Comment by alexsomesan** [comment]
@pdecat I think changing `port` to no-default should avoid these issues. Not sure if it's necessary to mark as computed unless the client-go sets one even if it hasn't received it from the API.
I'll experiment with that a bit later.

**Comment by pdecat** [comment]
I did some tests and computed is indeed not needed.

**Comment by pdecat** [comment]
After thinking a bit more about this, I believe defaults should only implemented by the terraform provider if they are exposed by the kubernetes API

**Comment by alexsomesan** [comment]
I've always been working on that assumption, but I have to admit in this case I didn't check if the default is actually also implemented by the API.

**Comment by pdecat** [comment]
We could probably have additional acceptance tests to ensure this is the case each time a new field is introduced. 

What about opening an umbrella issue to track where defaults are set by terraform, but originally not exposed by the kubernetes API?

**Comment by jrsherry** [comment]
Would it also be possible to document the k8s versions that passed acceptance testing with each release of the provider?

**Comment by pdecat** [comment]
Turns out in the case of APIService `port`, the default is actually exposed, I even added an assertion about that: https://github.com/terraform-providers/terraform-provider-kubernetes/blob/38cd40baa7389ea9d216b1261a61e038dfa8b713/kubernetes/resource_kubernetes_api_service_test.go#L37

An example of a _not exposed_ default is the `mount_propagation` field on volume blocks: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/552#issuecomment-551942469

**Comment by pdecat** [comment]
> @pdecat I think changing `port` to no-default should avoid these issues. Not sure if it's necessary to mark as computed unless the client-go sets one even if it hasn't received it from the API.

When removing defaults, marking the field as `Computed` should avoid issues like https://github.com/terraform-providers/terraform-provider-kubernetes/pull/275#issuecomment-552588625

**Comment by pdecat** [comment]
> Turns out in the case of APIService `port`, the default is actually exposed, I even added an assertion about that: https://github.com/terraform-providers/terraform-provider-kubernetes/blob/38cd40baa7389ea9d216b1261a61e038dfa8b713/kubernetes/resource_kubernetes_api_service_test.go#L37

:man_facepalming: it is more subtle than that...

A way to actually have an acceptance test that checks if a default is exposed by the API could be to:
- check if a resource field has its `Default` field set to a non-nil value in the schema,
- if so, store that default value in a temporary variable and dynamically alter the resource schema to:
  - set the `Default` field to `nil`,
  - set the `Computed` field to `true`,
  - apply a configuration that does not have the resource field set,
  - assert that the value returned by the API is equal to the one originally defined as the default in the schema.

I'll experiment with this.

Note: this will be a bit more complicated to do with `DefaultFunc`.

**Pull request merged**
