### PR TITLE
Add support for ClusterRoleBinding

### PR DESCRIPTION
**Pull request by micahhausler**
Re-create of #1, Fixes hashicorp/terraform#15194

@radeksimko I'll rebase once 1.8 is in `/vendor`

### CODE REVIEW

**Comment by munnerz** [comment]
Any update on this? This is a missing piece for a number of projects of mine!

I'd be happy to take on the rebasing work etc.

**Comment by marksost** [comment]
Hey @micahhausler and @radeksimko! I'm in a similar position as @munnerz above. Anything I can do to help?

**Comment by Mistobaan** [comment]
need this as well on gke. How are you guys solving in the mean time, @munnerz @marksost ?

**Comment by marksost** [comment]
@Mistobaan nothing great to report currently. Been playing around with the [Kubernetes Ansible module](http://docs.ansible.com/ansible/latest/kubernetes_module.html) to apply a declaration we wrote, but it's far from bulletproof and means we need multiple tools and then glue code to tie them together in the right order.

This feature would be super helpful.

**Comment by jhoblitt** [comment]
It looks like this resource is a blocker to being able to setup helm / user the tf helm provider with any k8s cluster that has RBAC enabled, which is gke from at least 1.7.x-gke on.

**Comment by jhoblitt** [comment]
Is the travis setup broken?

**Comment by marksost** [comment]
@jhoblitt I believe it's throwing an error from a non-vendored package.

```
kubernetes/resource_kubernetes_cluster_role_binding.go:11:2: cannot find package "k8s.io/kubernetes/pkg/apis/rbac/v1" in any of:
  /home/travis/gopath/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/k8s.io/kubernetes/pkg/apis/rbac/v1 (vendor tree)
  /home/travis/.gimme/versions/go1.9.linux.amd64/src/k8s.io/kubernetes/pkg/apis/rbac/v1 (from $GOROOT)
  /home/travis/gopath/src/k8s.io/kubernetes/pkg/apis/rbac/v1 (from $GOPATH)
kubernetes/resource_kubernetes_cluster_role_binding.go:12:2: cannot find package "k8s.io/kubernetes/pkg/client/clientset_generated/clientset" in any of:
  /home/travis/gopath/src/github.com/terraform-providers/terraform-provider-kubernetes/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (vendor tree)
  /home/travis/.gimme/versions/go1.9.linux.amd64/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (from $GOROOT)
  /home/travis/gopath/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset (from $GOPATH)
```

Checking the tree, that package doesn't appear to be present: https://github.com/micahhausler/terraform-provider-kubernetes/tree/f-k8s-clusterrolebinding/vendor/k8s.io

**Comment by jhoblitt** [comment]
Good catch.  It looks like https://github.com/terraform-providers/terraform-provider-kubernetes/pull/117 will pull that in.

**Comment by micahhausler** [comment]
Yea the Travis error is a package problem. I didn't want to bloat this PR with upgrading the whole k8s client.

**Comment by marksost** [comment]
Hey @micahhausler and @radeksimko, wanted to see if support for this might be coming any time soon? Any workaround you'd suggest in the meantime?

**Comment by obeyler** [comment]
@micahhausler and @radeksimko, Do you think that this functionnality will arrive soon ? RBAC is need to be able to deploy Kubernetes dashboard for example. 
As @marksost asked before, is there any workaround or help we can do  ?

**Comment by brandoconnor** [comment]
Working with AWS EKS through Terraform and finding the kubernetes provider is currently unusable in this set up (k8s cluster is 1.10) as the user grabbed from the generated . I gather it's due to recent k8s RBAC changes which renders the user `system:anonymous` unable to do anything.

```
<resource_type> is forbidden: User "system:anonymous"...
```

I would guess there's a separate issue (or user error) of being able to authenticate using the provided user specified in the kubeconfig and leveraging heptio-authenticator but also, the first steps to creating a useful demo requires creating an admin user that can access the dashboard which requires calls to both ClusterRoleBinding and ServiceAccount.

**Comment by costimuraru** [comment]
Hey guys! What's the status on adding support for ClusterRoleBinding in the terraform k8s provider?

**Comment by v00d00** [comment]
Another month has passed, clearly there is a lot of interest in getting this merged?

Can we at least have the steps required to get this included listed out so we can start working through them?

**Comment by micahhausler** [comment]
The  only thing blocking this is an updated K8s client library. 

#117 - 1.9
#162 - 1.10

Once one of those are merged, I can update the import paths to make this work

**Comment by ariefrahmansyah** [comment]
Thanks @micahhausler!
Btw, how about ClusterRole? We need to create new ClusterRole first before bind it.
If not, I would like to create PR for this.

**Comment by adamdecaf** [comment]
> kubernetes/resource_kubernetes_cluster_role_binding.go:11:2: cannot find package "k8s.io/kubernetes/pkg/apis/rbac/v1" in any of:

It looks like the dependencies need to be updated. Could someone with access to the PR bump those?

**Comment by Starefossen** [comment]
Yes, need ClusterRole and ClusterRoleBinding in order to set up dynamic [Persistent Volume Claims using Azure File](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) 😄

**Comment by alexsomesan** [comment]
@micahhausler Many apologies for the amount of time this PR has been sitting still. I will be taking care of the K8S provider moving forward. I would like to help you get this merged.

The PR to update K8S client packages to 1.10 has been merge, so from that POV you're unblocked.
I've had a quick go at rebasing this branch to current master is the following changes were needed to get it to build.

```

**Comment by alexsomesan** [comment]
Also please have a look at the acceptance tests specific to this new resouce. On a quick run on my machine they fail.
Here's the output:
```
TESTARGS="-run ^TestAccKubernetesClusterRoleBinding.*$" make testacc                      alex@alexs-macbook
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run ^TestAccKubernetesClusterRoleBinding.* -timeout 120m
?   	github.com/terraform-providers/terraform-provider-kubernetes	[no test files]
=== RUN   TestAccKubernetesClusterRoleBinding
--- FAIL: TestAccKubernetesClusterRoleBinding (0.08s)
	testing.go:518: Step 0 error: Check failed: 3 error(s) occurred:

		* Check 12/14 error: kubernetes_cluster_role_binding.test: Attribute 'subject.0.api_group' not found
		* Check 13/14 error: kubernetes_cluster_role_binding.test: Attribute 'subject.0.name' not found
		* Check 14/14 error: kubernetes_cluster_role_binding.test: Attribute 'subject.0.kind' not found
=== RUN   TestAccKubernetesClusterRoleBinding_importBasic
--- FAIL: TestAccKubernetesClusterRoleBinding_importBasic (0.07s)
	testing.go:518: Step 0 error: After applying this step, the plan was not empty:

		DIFF:

		UPDATE: kubernetes_cluster_role_binding.test
		  subject.0.api_group: "" => "rbac.authorization.k8s.io"
		  subject.0.kind:      "" => "User"
		  subject.0.name:      "" => "notauser"
		  subject.0.namespace: "" => "default"

		STATE:

		kubernetes_cluster_role_binding.test:
		  ID = tf-acc-test-c0z0mr2ci3
		  provider = provider.kubernetes
		  metadata.# = 1
		  metadata.0.annotations.% = 0
		  metadata.0.generation = 0
		  metadata.0.labels.% = 0
		  metadata.0.name = tf-acc-test-c0z0mr2ci3
		  metadata.0.resource_version = 31130
		  metadata.0.self_link = /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/tf-acc-test-c0z0mr2ci3
		  metadata.0.uid = 20af46f4-c830-11e8-ac4d-feb8ddfbfc24
		  role_ref.% = 3
		  role_ref.api_group = rbac.authorization.k8s.io
		  role_ref.kind = ClusterRole
		  role_ref.name = cluster-admin
		  subject.# = 1
FAIL
FAIL	github.com/terraform-providers/terraform-provider-kubernetes/kubernetes	0.760s
make: *** [testacc] Error 1
```

**Comment by alexsomesan** [comment]
@micahhausler I hope you don't mind if I go ahead and make the small changes needed to get this PR in shape for merges. I'd really like to get it in, now that we can.

**Comment by micahhausler** [comment]
Not at all, I'm in an on-call rotation and pretty busy this week

**Comment by alexsomesan** [comment]
@micahhausler That's all good! Thanks for the acknowledgement.
I know AWS on-call shifts, been there :)

**Comment by jhoblitt** [comment]
Woot! Thanks folks!

**Comment by marksost** [comment]
Yes, thanks everyone for the work to push this through!

**Comment by jmjava** [comment]
i cloned master and tried using this:

resource "kubernetes_cluster_role_binding" "helm" { 
	metadata { 
		name = "helm"
	} 
	role_ref { 
		api_group = "rbac.authorization.k8s.io" 
		kind = "ClusterRole" 
		name = "cluster-admin" 
	} 
	subject { 
		kind = "ServiceAccount"
		name = "helm" 
		api_group = "rbac.authorization.k8s.io"
		namespace = "kube-system"
	} 
}

I am getting this:

Error: kubernetes_cluster_role_binding.helm: Provider doesn't support resource: kubernetes_cluster_role_binding

**Comment by alexsomesan** [comment]
@jmjava Did you install the provider after build? (Usually under ~/.terraform.d/plugins/)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jmjava** [comment]
> @jmjava Did you install the provider after build? (Usually under ~/.terraform.d/plugins/)
> 
> Sent with [GitHawk](http://githawk.com)

Thanks... YES --that was the issue.  The version downloaded automatically from the web was being used. I did something similar to fix it.  Will try your way next time :)  

Thanks for this work. 

-john

**Comment by cdaguerre** [comment]
Hi, I built the provider and moved it to `~/.terraform/plugins` and get the following error when trying to create a ClusterRoleBinding:

```sh
module.platform-cluster.kubernetes_cluster_role_binding.tiller: Creating...
  metadata.#:                  "" => "1"
  metadata.0.generation:       "" => "<computed>"
  metadata.0.name:             "" => "tiller-clusterrolebinding"
  metadata.0.resource_version: "" => "<computed>"
  metadata.0.self_link:        "" => "<computed>"
  metadata.0.uid:              "" => "<computed>"
  role_ref.%:                  "" => "3"
  role_ref.api_group:          "" => "rbac.authorization.k8s.io"
  role_ref.kind:               "" => "ClusterRole"
  role_ref.name:               "" => "cluster-admin"
  subject.#:                   "" => "1"
  subject.0.api_group:         "" => "rbac.authorization.k8s.io"
  subject.0.kind:              "" => "ServiceAccount"
  subject.0.name:              "" => "tiller"
  subject.0.namespace:         "" => "kube-system"

Error: Error applying plan:

1 error(s) occurred:

* module.platform-cluster.kubernetes_cluster_role_binding.tiller: 1 error(s) occurred:

* kubernetes_cluster_role_binding.tiller: ClusterRoleBinding.rbac.authorization.k8s.io "tiller-clusterrolebinding" is invalid: subjects[0].apiGroup: Unsupported value: "rbac.authorization.k8s.io": supported values: ""

**Comment by olib963** [comment]
@cdaguerre I believe the `api_group` for the subject must be an empty string but must be `"rbac.authorization.k8s.io"` for `role_ref`

**Comment by alexsomesan** [comment]
@cdaguerre `ServiceAccount` are actually a core ApiGroup resource, not an RBAC one, so they need `api_group` set to "" explicitly when used as subjects. 

This is because this resource right now defaults to `api_group = "rbac.authorization.k8s.io"` when none is actually specified. I'm on the fence whether this is a viable approach, but I want to collect more user feedback before making a decision about changing that.

**Comment by ntrp** [comment]
I think a better approach would be to set default empty and allow users to configure it for the `role_ref`. Like it's now it is confusing in my opinion..

On top of that [here](https://www.terraform.io/docs/providers/kubernetes/r/cluster_role_binding.html) is written that it applies only to `User` and `Group` but it's not written that for `ServiceAccount` it must be empty.

**Comment by RobMaskell** [comment]
As part of this PR was a resource added for "kubernetes_cluster_role"? 
I'm trying to do the equiv of this 
```
kubectl create clusterrole nm-secret-writer --verb=get,list,create,update --resource=secrets
```
and I can't see it in the docs

**Comment by mogggggg** [comment]
I would like to know this too, it looks like the Kubernetes provider can do everything I need except for the creation of roles

**Pull request merged**
