### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by nickschuch**
Deployments have now become stable as a part of release [v1.9.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md)

This pull request is a few things:

* Asking if you this project is now interesting in accepting the `kubernetes_deployment` resource now that 1.9.0 has landed.
* If I am on the right path with this approach. I still have quite a bit of polish to put on this so wanted to ask early.

This is my first contribution to the Terraform community so would love to hear any feedback you want to give!

I am also very interested in also contributing the "DaemonSet" resource!

I used `dep` to bump the client libraries up to "release-1.9.0". Would you be interested in switching to Dep or is there some guidance I could get on bumping with go-vendor?

### CODE REVIEW

**Comment by sl1pm4t** [comment]
@nickschuch - just a heads up, most of the (previously beta) workload resources have already been developed and are available in various community forks of this provider. 
I've collected most/all of them up in the `custom` branch of my [fork](github.com/sl1pm4t/terraform-provider-kubernetes) and added some resources myself, so I recommend you check it out before spending too much developing them from scratch.
It has DaemonSet, Deployment, StatefulSet, Ingress etc.

Some of them still need documentation and acceptance tests, but are otherwise fully functional. We've been using the Deployment in our production environment for a few months.

I'll also start sending PR's across to this repo now that these resources are GA.

**Comment by nickschuch** [comment]
No worries, looking at the fork I can see a few things:

* Schema is missing a bunch of fields
* Modeled off the replica, which we will want it to use more "Deployment" style logic to wait for when its finished. (That code can be found in the kubelet).

Would you be open to a collaboration?

**Comment by sl1pm4t** [comment]
@nickschuch - yes happy to Collaborate. 
Are you able to update the vendored Kubernetes client packages using `govendor`, which seems to be the preferred vendoring tool of Hashicorp / Terraform.
I'll then send a PR for the `kubernetes_deployment` resource in my fork, and we can beat it into shape.

**Comment by nickschuch** [comment]
No worries! Ill get `govendor` another crack today and report back.

**Comment by dmathieu** [comment]
@nickschuch do you need help finishing this PR?

**Comment by nickschuch** [comment]
Hey hey! That would be great. I will be back onto my regular schedule programming next week :)

**Comment by moritzheiber** [comment]
Can we get this baby on the road? :slightly_smiling_face:

**Comment by travisjeffery** [comment]
I've wrote a version for us at Confluent we've had shipped in prod for months now. I'll ship it this week.

**Comment by nickschuch** [comment]
Yup, I have one here as well https://github.com/previousnext/terraform-provider-k8s (has a bunch of missing APIs).

I will revisit this issue this week.

**Comment by acobaugh** [comment]
@sl1pm4t I'm also willing to help test, as I desperately need the deployment resource. I'm making do with your fork, but I've already found a bug (can't set strategy type to "Recreate"). Let me know what I can do to help or file issues.

**Comment by joshperry** [comment]
I'm happy to pitch in as well. Can we come to an agreement on a fork to pursue so that I'm not wasting cycles? I did about a 1/3 impl before I saw this PR, so I'm somewhat fresh with the codebase.

**Comment by pdecat** [comment]
Hi @nickschuch,

> I used dep to bump the client libraries up to "release-1.9.0". Would you be interested in switching to Dep or is there some guidance I could get on bumping with go-vendor?

I was looking into doing the same and found out the upgrade from client-go v4 to v5+ is not that easy.
Nice work!

What would you think about submitting a separate PR to upgrade the client libs with only those two commits?

https://github.com/nickschuch/terraform-provider-kubernetes/commit/c7dcbf2abb2aa8ced4b2c88fa7f9b8458aaf061d
https://github.com/nickschuch/terraform-provider-kubernetes/commit/aaff7e9c1dcbd73f716e77aff784886fda0538a8

**Comment by djhaskin987** [comment]
Just wanted to ask if there's anything I can do to help with this PR . I'm a huge fan of getting this done

**Comment by austinkelleher** [comment]
@radeksimko What is it going to take to get this merged? This PR has been open for 2.5 months and really is crucial to using the Kubernetes Terraform provider for many applications.

**Comment by bassrock** [comment]
@austinkelleher Look at https://github.com/sl1pm4t/terraform-provider-kubernetes it has deployments and more and is constantly maintained with these upstream changes.

**Comment by austinkelleher** [comment]
@bassrock I'm currently using that, but I'd really like to see deployments becoming a part of core `terrafor-provider-kubernetes`. There's no reason why a fork should have to be maintained at this point. The original argument for not allowing these changes into the core provider plugin was because Kubernetes deployments were in a beta API. Now this feature is out of beta and is a part of the `v1` API version.

/cc @radeksimko

**Comment by george-oakling** [comment]
Yes, please, make it to mainline :)

**Comment by peterver** [comment]
using the custom one as well at the moment, but would love seeing this in mainline as well :)

**Comment by costimuraru** [comment]
👍 would love to see this merged

**Comment by jaceq** [comment]
Any update here?

**Comment by alexsomesan** [comment]
@nickschuch We've recently merged an update of the K8S client libraries to 1.10.
Would you be able to rebase this PR and remove the `dep` vendoring commit (you'll be able to make use of the newly merged client libraries).
We plan to switch dependency management to Go modules quite soon.

**Comment by nickschuch** [comment]
Thanks @alexsomesan ! I'll sort it out today!

**Comment by nickschuch** [comment]
Rebased!

How shall I proceed?

**Comment by alexsomesan** [comment]
@nickschuch Looks good. Do you have anymore changes you'd like to add to this PR? 

Otherwise I would say we merge it and work on acceptance tests, which are missing. Normally we'd not merge a PR without any kind of tests, but since this has been sitting for so long and we'd like to get the ball rolling again with the K8S provider I feel we can work on tests next and merge it now.

**Comment by nickschuch** [comment]
That sounds great @alexsomesan !

**Comment by zimbatm** [comment]
OMG. Kubernetes Deployments in terraform!

**Comment by Starefossen** [comment]
Now we only need to get #73 merged and then we can have a party 🎉 Keep up the good work everyone ❤️

**Comment by adrianlop** [comment]
hey guys,

looks like docs weren't updated: https://www.terraform.io/docs/providers/kubernetes/
but there's a new release of the kubernetes provider, so I guess the `Deployment` resource is available?

can anyone confirm please?
thank you in advance!

**Comment by alexsomesan** [comment]
@adrianlop This is true. Issue was caused by me not being familiar with the website deployment process.
I'm in the middle of fixing it.

**Comment by alexsomesan** [comment]
Done. Deployment docs are here: https://www.terraform.io/docs/providers/kubernetes/r/deployment.html

**Comment by adrianlop** [comment]
that was fast mate @alexsomesan thank you very much!!

**Comment by enozero** [comment]
I'm looking at the update portion. Once it has updated the deployment, it seems it calls `waitForDesiredReplicasFunc` rather than `waitForDeploymentReplicasFunc`. Was this desired? I'm getting an issue where the replicationcontroller is not created and the `apply` fails.

**Comment by alexsomesan** [comment]
@enozero Let me take a look...

**Comment by enozero** [comment]
Thanks, @alexsomesan! I filed https://github.com/terraform-providers/terraform-provider-kubernetes/issues/210 to track.

**Pull request merged**
