### PR TITLE
Upgrade k8s client libs to 1.9

### PR DESCRIPTION
**Pull request by pdecat**
I've managed to upgrade the k8s client libs to 1.9 in five steps with govendor:

1. Cherry-pick of @nickschuch's https://github.com/nickschuch/terraform-provider-kubernetes/commit/aaff7e9c1dcbd73f716e77aff784886fda0538a8 (`Update github.com/terraform-providers/terraform-provider-kubernetes to use k8s/client-go 1.9.0`)
1. `govendor fetch k8s.io/...`
1. Fix Flex persistent volume flattener/expander functions after upgrade of k8s libs to 1.9
1. `govendor remove +m`
1. `govendor remove k8s.io/apimachinery/pkg/apis/meta/v1alpha1`

### CODE REVIEW

**Comment by pdecat** [comment]
# Unit tests results

```
#  make test
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
        xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-kubernetes github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 
?       github.com/terraform-providers/terraform-provider-kubernetes    [no test files]
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 0.030s
```

**Comment by pdecat** [comment]
# Acceptance tests results with local minikube

```
# make testacc TEST=./kubernetes                                                                                              
==> Checking that code complies with gofmt requirements...                                                                          
TF_ACC=1 go test ./kubernetes -v  -timeout 120m                                                                                     
=== RUN   TestAccKubernetesDataSourceService_basic                                                                                                                                                                                                                       
--- PASS: TestAccKubernetesDataSourceService_basic (0.17s)                                                                          
=== RUN   TestAccKubernetesDataSourceStorageClass_basic                                                                             
--- PASS: TestAccKubernetesDataSourceStorageClass_basic (0.12s)                                                                                                                                                                                                          
=== RUN   TestDiffStringMap                                                                                                         
=== RUN   TestDiffStringMap/0                                                                                                       
=== RUN   TestDiffStringMap/1                                                                                                                                                                                                                                            
=== RUN   TestDiffStringMap/2                                     
=== RUN   TestDiffStringMap/3                                                                                                       
=== RUN   TestDiffStringMap/4                                                                                                                                                                                                                                            
=== RUN   TestDiffStringMap/5                                                                                                       
=== RUN   TestDiffStringMap/6                                                                                                       
--- PASS: TestDiffStringMap (0.00s)                                                                                                                                                                                                                                      
    --- PASS: TestDiffStringMap/0 (0.00s)                                                                                           
    --- PASS: TestDiffStringMap/1 (0.00s)                                                                                           
    --- PASS: TestDiffStringMap/2 (0.00s)                                                                                                                                                                                                                                
    --- PASS: TestDiffStringMap/3 (0.00s)                         
    --- PASS: TestDiffStringMap/4 (0.00s)                                                                                           
    --- PASS: TestDiffStringMap/5 (0.00s)                         
    --- PASS: TestDiffStringMap/6 (0.00s)                         
=== RUN   TestEscapeJsonPointer                                   
--- PASS: TestEscapeJsonPointer (0.00s)                           
=== RUN   TestProvider                                            
--- PASS: TestProvider (0.01s)                                    
=== RUN   TestProvider_impl                                       
--- PASS: TestProvider_impl (0.00s)                               
=== RUN   TestProvider_configure                                                                                                    
--- PASS: TestProvider_configure (0.00s)                                                                                            
=== RUN   TestAccKubernetesConfigMap_basic                                                                                          
--- PASS: TestAccKubernetesConfigMap_basic (0.20s)                                                                                  
=== RUN   TestAccKubernetesConfigMap_importBasic                                                                                    
--- PASS: TestAccKubernetesConfigMap_importBasic (0.11s)                                                                            
=== RUN   TestAccKubernetesConfigMap_generatedName                
--- PASS: TestAccKubernetesConfigMap_generatedName (0.09s)        
=== RUN   TestAccKubernetesConfigMap_importGeneratedName          
--- PASS: TestAccKubernetesConfigMap_importGeneratedName (0.09s)                                                                    
=== RUN   TestAccKubernetesHorizontalPodAutoscaler_basic          
--- PASS: TestAccKubernetesHorizontalPodAutoscaler_basic (0.22s)  
=== RUN   TestAccKubernetesHorizontalPodAutoscaler_generatedName  
--- PASS: TestAccKubernetesHorizontalPodAutoscaler_generatedName (0.10s)                                                            
=== RUN   TestAccKubernetesHorizontalPodAutoscaler_importBasic    
--- PASS: TestAccKubernetesHorizontalPodAutoscaler_importBasic (0.11s)                                                              
=== RUN   TestAccKubernetesLimitRange_basic                       
--- PASS: TestAccKubernetesLimitRange_basic (0.26s)               
=== RUN   TestAccKubernetesLimitRange_generatedName               
--- PASS: TestAccKubernetesLimitRange_generatedName (0.10s)       
=== RUN   TestAccKubernetesLimitRange_typeChange                  
--- PASS: TestAccKubernetesLimitRange_typeChange (0.17s)          
=== RUN   TestAccKubernetesLimitRange_multipleLimits                                                                                
--- PASS: TestAccKubernetesLimitRange_multipleLimits (0.13s)      
=== RUN   TestAccKubernetesLimitRange_importBasic                 
--- PASS: TestAccKubernetesLimitRange_importBasic (0.10s)         
=== RUN   TestAccKubernetesNamespace_basic                        
--- PASS: TestAccKubernetesNamespace_basic (6.51s)                                                                                                                                                                                                                       
=== RUN   TestAccKubernetesNamespace_importBasic                                                                                                                                                                                                                         
--- PASS: TestAccKubernetesNamespace_importBasic (6.36s)                                                                                                                                                                                                                 
=== RUN   TestAccKubernetesNamespace_generatedName                                                                                                                                                                                                                       
--- PASS: TestAccKubernetesNamespace_generatedName (6.34s)                                                                                                                                                                                                               
=== RUN   TestAccKubernetesNamespace_withSpecialCharacters                                                                                                                                                                                                               
--- PASS: TestAccKubernetesNamespace_withSpecialCharacters (6.34s)                                                                                                                                                                                                       
=== RUN   TestAccKubernetesNamespace_importGeneratedName                                                                                                                                                                                                                 
--- PASS: TestAccKubernetesNamespace_importGeneratedName (6.34s)                                                                                                                                                                                                         
=== RUN   TestAccKubernetesPersistentVolumeClaim_basic                                                                                                                                                                                                                   
--- FAIL: TestAccKubernetesPersistentVolumeClaim_basic (0.37s)                                                                                                                                                                                                           
        testing.go:449: Step 5 error: Check failed: 1 error(s) occurred:                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                         
                * Check 1/1 error: tf-acc-test-fuovqdut7i annotations don't match.                                                                                                                                                                                       
                Expected: map["TestAnnotationOne":"one" "TestAnnotationTwo":"two" "volume.beta.kubernetes.io/storage-provisioner":"k8s.io/minikube-hostpath"]                                                                                                            
                Given: map["pv.kubernetes.io/bind-completed":"yes" "pv.kubernetes.io/bound-by-controller":"yes" "volume.beta.kubernetes.io/storage-provisioner":"k8s.io/minikube-hostpath" "TestAnnotationOne":"one" "TestAnnotationTwo":"two" "control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"81e9557c-0e92-11e8-b2cb-08002770080c\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2018-02-13T23:09:28Z\",\"renewTime\":\"2018-02-13T23:09:28Z\",\"leaderTransitions\":1}"]                                                    
=== RUN   TestAccKubernetesPersistentVolumeClaim_googleCloud_importBasic                                                                                                                                                                                                 
--- SKIP: TestAccKubernetesPersistentVolumeClaim_googleCloud_importBasic (0.00s)                                                                                                                                                                                         
        provider_test.go:183: The environment variables GOOGLE_PROJECT, GOOGLE_REGION and GOOGLE_ZONE must be set to run Google Cloud tests - skipping                                                                                                                   
=== RUN   TestAccKubernetesPersistentVolumeClaim_googleCloud_volumeMatch                                                                                                                                                                                                 
--- SKIP: TestAccKubernetesPersistentVolumeClaim_googleCloud_volumeMatch (0.00s)                                                                                                                                                                                         
        provider_test.go:183: The environment variables GOOGLE_PROJECT, GOOGLE_REGION and GOOGLE_ZONE must be set to run Google Cloud tests - skipping                                                                                                                   
=== RUN   TestAccKubernetesPersistentVolumeClaim_googleCloud_volumeUpdate                                                                                                                                                                                                
--- SKIP: TestAccKubernetesPersistentVolumeClaim_googleCloud_volumeUpdate (0.00s)                                                                                                                                                                                        
        provider_test.go:183: The environment variables GOOGLE_PROJECT, GOOGLE_REGION and GOOGLE_ZONE must be set to run Google Cloud tests - skipping                                                                                                                   
=== RUN   TestAccKubernetesPersistentVolumeClaim_googleCloud_storageClass                                                                                                                                                                                                
--- SKIP: TestAccKubernetesPersistentVolumeClaim_googleCloud_storageClass (0.00s)                                                                                                                                                                                        
        provider_test.go:183: The environment variables GOOGLE_PROJECT, GOOGLE_REGION and GOOGLE_ZONE must be set to run Google Cloud tests - skipping                                                                                                                   
=== RUN   TestAccKubernetesPersistentVolume_googleCloud_basic                                                                                                                                                                                                            
--- SKIP: TestAccKubernetesPersistentVolume_googleCloud_basic (0.00s)                                                                                                                                                                                                    
        provider_test.go:183: The environment variables GOOGLE_PROJECT, GOOGLE_REGION and GOOGLE_ZONE must be set to run Google Cloud tests - skipping                                                                                                                   
=== RUN   TestAccKubernetesPersistentVolume_googleCloud_importBasic                                                                                                                                                                                                      
--- SKIP: TestAccKubernetesPersistentVolume_googleCloud_importBasic (0.00s)                                                                                                                                                                                              
        provider_test.go:183: The environment variables GOOGLE_PROJECT, GOOGLE_REGION and GOOGLE_ZONE must be set to run Google Cloud tests - skipping                                                                                                                   
=== RUN   TestAccKubernetesPersistentVolume_googleCloud_volumeSource                                                                                                                                                                                                     
--- SKIP: TestAccKubernetesPersistentVolume_googleCloud_volumeSource (0.00s)                                                                                                                                                                                             
        provider_test.go:183: The environment variables GOOGLE_PROJECT, GOOGLE_REGION and GOOGLE_ZONE must be set to run Google Cloud tests - skipping                                                                                                                   
=== RUN   TestAccKubernetesPersistentVolume_cephFsSecretRef                                                                                                                                                                                                              
--- PASS: TestAccKubernetesPersistentVolume_cephFsSecretRef (0.31s)                                                                                                                                                                                                      
=== RUN   TestAccKubernetesPod_basic                                                                                                                                                                                                                                     
--- PASS: TestAccKubernetesPod_basic (10.93s)                                                                                                                                                                                                                            
=== RUN   TestAccKubernetesPod_updateForceNew                                                                                                                                                                                                                            
--- PASS: TestAccKubernetesPod_updateForceNew (90.53s)                                                                                                                                                                                                                   
=== RUN   TestAccKubernetesPod_importBasic                                                                                                                                                                                                                               
--- PASS: TestAccKubernetesPod_importBasic (28.70s)                                                                                                                                                                                                                      
=== RUN   TestAccKubernetesPod_with_pod_security_context                                                                                                                                                                                                                 
--- PASS: TestAccKubernetesPod_with_pod_security_context (9.04s)                                                                                                                                                                                                         
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_exec                                                                                                                                                                                                  
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_exec (38.68s)                                                                                                                                                                                         
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_http_get                                                                                                                                                                                              
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_http_get (10.67s)                                                                                                                                                                                     
=== RUN   TestAccKubernetesPod_with_container_liveness_probe_using_tcp                                                                                                                                                                                                   
--- PASS: TestAccKubernetesPod_with_container_liveness_probe_using_tcp (9.05s)                                                                                                                                                                                           
=== RUN   TestAccKubernetesPod_with_container_lifecycle                                                                                                                                                                                                                  
--- PASS: TestAccKubernetesPod_with_container_lifecycle (6.71s)                                                                                                                                                                                                          
=== RUN   TestAccKubernetesPod_with_container_security_context                                                                                                                                                                                                           
--- PASS: TestAccKubernetesPod_with_container_security_context (3.03s)                                                                                                                                                                                                   
=== RUN   TestAccKubernetesPod_with_volume_mount                                                                                                                                                                                                                         
--- PASS: TestAccKubernetesPod_with_volume_mount (6.69s)                                                                                                                                                                                                                 
=== RUN   TestAccKubernetesPod_with_cfg_map_volume_mount                                                                                                                                                                                                                 
--- PASS: TestAccKubernetesPod_with_cfg_map_volume_mount (17.13s)                                                                                                                                                                                                        
=== RUN   TestAccKubernetesPod_with_resource_requirements                                                                                                                                                                                                                
--- PASS: TestAccKubernetesPod_with_resource_requirements (6.65s)                                                                                                                                                                                                        
=== RUN   TestAccKubernetesPod_with_empty_dir_volume                                                                                                                                                                                                                     
--- PASS: TestAccKubernetesPod_with_empty_dir_volume (5.07s)                                                                                                                                                                                                             
=== RUN   TestAccKubernetesPod_with_secret_vol_items                                                                                                                                                                                                                     
--- PASS: TestAccKubernetesPod_with_secret_vol_items (6.70s)                                                                                                                                                                                                             
=== RUN   TestAccKubernetesPod_gke_with_nodeSelector                                                                                                                                                                                                                     
--- SKIP: TestAccKubernetesPod_gke_with_nodeSelector (0.00s)                                                                                                                                                                                                             
        provider_test.go:206: The Kubernetes endpoint must come from GKE for this test to run - skipping                                                                                                                                                                 
=== RUN   TestAccKubernetesReplicationController_basic                                                                                                                                                                                                                   
--- PASS: TestAccKubernetesReplicationController_basic (128.55s)                                                                                                                                                                                                         
=== RUN   TestAccKubernetesReplicationController_importBasic                                                                                                                                                                                                             
--- PASS: TestAccKubernetesReplicationController_importBasic (118.47s)                                                              
=== RUN   TestAccKubernetesReplicationController_generatedName    
--- PASS: TestAccKubernetesReplicationController_generatedName (1.23s)                                                              
=== RUN   TestAccKubernetesReplicationController_importGeneratedName                                                                
--- PASS: TestAccKubernetesReplicationController_importGeneratedName (1.33s)                                                        
=== RUN   TestAccKubernetesReplicationController_with_security_context                                                              
--- PASS: TestAccKubernetesReplicationController_with_security_context (1.26s)                                                      
=== RUN   TestAccKubernetesReplicationController_with_container_liveness_probe_using_exec                                           
--- PASS: TestAccKubernetesReplicationController_with_container_liveness_probe_using_exec (1.30s)                                   
=== RUN   TestAccKubernetesReplicationController_with_container_liveness_probe_using_http_get                                       
--- PASS: TestAccKubernetesReplicationController_with_container_liveness_probe_using_http_get (1.33s)                               
=== RUN   TestAccKubernetesReplicationController_with_container_liveness_probe_using_tcp                                            
--- PASS: TestAccKubernetesReplicationController_with_container_liveness_probe_using_tcp (1.32s)                                    
=== RUN   TestAccKubernetesReplicationController_with_container_lifecycle                                                           
--- PASS: TestAccKubernetesReplicationController_with_container_lifecycle (1.27s)                                                   
=== RUN   TestAccKubernetesReplicationController_with_container_security_context                                                    
--- PASS: TestAccKubernetesReplicationController_with_container_security_context (1.44s)                                            
=== RUN   TestAccKubernetesReplicationController_with_volume_mount
--- PASS: TestAccKubernetesReplicationController_with_volume_mount (1.51s)                                                          
=== RUN   TestAccKubernetesReplicationController_with_resource_requirements                                                         
--- PASS: TestAccKubernetesReplicationController_with_resource_requirements (1.32s)                                                 
=== RUN   TestAccKubernetesReplicationController_with_empty_dir_volume                                                                                                                                                                                                   
--- PASS: TestAccKubernetesReplicationController_with_empty_dir_volume (1.28s)                                                                                                                                                                                           
=== RUN   TestAccKubernetesResourceQuota_basic                                                                                                                                                                                                                           
--- PASS: TestAccKubernetesResourceQuota_basic (1.32s)
=== RUN   TestAccKubernetesResourceQuota_generatedName
--- PASS: TestAccKubernetesResourceQuota_generatedName (0.11s)
=== RUN   TestAccKubernetesResourceQuota_withScopes
--- PASS: TestAccKubernetesResourceQuota_withScopes (1.19s)
=== RUN   TestAccKubernetesResourceQuota_importBasic
--- PASS: TestAccKubernetesResourceQuota_importBasic (0.60s)
=== RUN   TestAccKubernetesSecret_basic
--- PASS: TestAccKubernetesSecret_basic (0.30s)
=== RUN   TestAccKubernetesSecret_importBasic
--- PASS: TestAccKubernetesSecret_importBasic (0.10s)
=== RUN   TestAccKubernetesSecret_generatedName
--- PASS: TestAccKubernetesSecret_generatedName (0.09s)
=== RUN   TestAccKubernetesSecret_importGeneratedName
--- PASS: TestAccKubernetesSecret_importGeneratedName (0.12s)
=== RUN   TestAccKubernetesServiceAccount_basic
--- PASS: TestAccKubernetesServiceAccount_basic (0.78s)
=== RUN   TestAccKubernetesServiceAccount_update
--- PASS: TestAccKubernetesServiceAccount_update (0.94s)
=== RUN   TestAccKubernetesServiceAccount_generatedName
--- PASS: TestAccKubernetesServiceAccount_generatedName (0.61s)
=== RUN   TestAccKubernetesService_basic
--- PASS: TestAccKubernetesService_basic (0.22s)
=== RUN   TestAccKubernetesService_loadBalancer
--- SKIP: TestAccKubernetesService_loadBalancer (0.00s)
        provider_test.go:195: The Kubernetes endpoint must come from an environment which supports load balancer provisioning for this test to run - skipping
=== RUN   TestAccKubernetesService_nodePort
--- PASS: TestAccKubernetesService_nodePort (0.16s)
=== RUN   TestAccKubernetesService_noTargetPort
--- SKIP: TestAccKubernetesService_noTargetPort (0.00s)
        provider_test.go:195: The Kubernetes endpoint must come from an environment which supports load balancer provisioning for this test to run - skipping
=== RUN   TestAccKubernetesService_externalName
--- PASS: TestAccKubernetesService_externalName (0.09s)
=== RUN   TestAccKubernetesService_importBasic
--- PASS: TestAccKubernetesService_importBasic (0.20s)
=== RUN   TestAccKubernetesService_generatedName
--- PASS: TestAccKubernetesService_generatedName (0.18s)
=== RUN   TestAccKubernetesService_importGeneratedName
--- PASS: TestAccKubernetesService_importGeneratedName (0.15s)
=== RUN   TestAccKubernetesStorageClass_basic
--- PASS: TestAccKubernetesStorageClass_basic (0.29s)
=== RUN   TestAccKubernetesStorageClass_importBasic
--- PASS: TestAccKubernetesStorageClass_importBasic (0.11s)
=== RUN   TestAccKubernetesStorageClass_generatedName
--- PASS: TestAccKubernetesStorageClass_generatedName (0.07s)
=== RUN   TestAccKubernetesStorageClass_importGeneratedName
--- PASS: TestAccKubernetesStorageClass_importGeneratedName (0.08s)
=== RUN   TestFlattenLabelSelector                                                                                                                                                                                                                                       
--- PASS: TestFlattenLabelSelector (0.00s) 
=== RUN   TestIsInternalKey                     
=== RUN   TestIsInternalKey/0                  
=== RUN   TestIsInternalKey/1                          
=== RUN   TestIsInternalKey/2                                                                                                                                
=== RUN   TestIsInternalKey/3              
=== RUN   TestIsInternalKey/4                      
=== RUN   TestIsInternalKey/5                  
=== RUN   TestIsInternalKey/6                          
--- PASS: TestIsInternalKey (0.00s)                                                                                                                          
    --- PASS: TestIsInternalKey/0 (0.00s)      
    --- PASS: TestIsInternalKey/1 (0.00s)              
    --- PASS: TestIsInternalKey/2 (0.00s)     
    --- PASS: TestIsInternalKey/3 (0.00s)             
    --- PASS: TestIsInternalKey/4 (0.00s)       
    --- PASS: TestIsInternalKey/5 (0.00s)               
    --- PASS: TestIsInternalKey/6 (0.00s)             
=== RUN   TestValidateModeBits                                
--- PASS: TestValidateModeBits (0.00s)       
FAIL                                                 
exit status 1                                      
FAIL    github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 553.490s
GNUmakefile:15: recipe for target 'testacc' failed   
make: *** [testacc] Error 1                                  
```

The `TestAccKubernetesPersistentVolumeClaim_basic` error about mismatching annotations also happens on master with minikube.

**Comment by jhoblitt** [comment]
This would certainly make me feel better about using tf with gke 1.9.3...

**Comment by zimbatm** [comment]
I tested this branch on GKE 1.9.4-gke.1 and it works great

**Comment by AndrewFarley** [comment]
*bump* Guys, Terraform is unusable against any well engineered Kubernetes cluster (with RBAC) without this and #73 and #162.  Can we please get some attention and get this stuff merged/completed soon?  This is almost a joke at this point

**Comment by pdecat** [comment]
Superseded by https://github.com/terraform-providers/terraform-provider-kubernetes/pull/162

**Pull request closed without merging**
