### PR TITLE
Add network policy resource

### LINKED ISSUE #110: Feature request: add kubernetes_network_policy resource
Please add support for Kubernetes NetworkPolicy resource.

### Affected Resource

- kubernetes_network_policy

### Terraform Configuration Files

```hcl
resource "kubernetes_namespace" "example" {
  metadata {
    name = "terraform-example-namespace"
  }
}

# NOT IMPLEMENTED YET
resource "kubernetes_network_policy" "allow_all" {
  metadata {
    name = "allow-all"
    namespace = "${kubernetes_namespace.example.metadata.0.name}"
  }

  spec {
    pod_selector = {}
    ingress = [{}]
    egress = [{}]
  }
}

```

### References

- API reference: https://kubernetes.io/docs/api-reference/v1.9/#networkpolicy-v1-networking

### PR DESCRIPTION
**Pull request by pdecat**
Resolves #110 

Checklist:
- [x] unit and acceptance tests passing
- [x] documentation added

### CODE REVIEW

**Comment by pdecat** [comment]
```
make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetesNetworkPolicy_*' 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetesNetworkPolicy_* -timeout 120m
=== RUN   TestAccKubernetesNetworkPolicy_basic
--- PASS: TestAccKubernetesNetworkPolicy_basic (0.25s)
=== RUN   TestAccKubernetesNetworkPolicy_importBasic
--- PASS: TestAccKubernetesNetworkPolicy_importBasic (0.09s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 0.432s
```

**Comment by pdecat** [comment]
# Unit tests results

```
# make test TEST=./kubernetes
==> Checking that code complies with gofmt requirements...
go test -i ./kubernetes || exit 1
echo ./kubernetes | \
        xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 ./kubernetes 
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 0.091s
```

# Acceptance tests results
```
# make testacc TEST=./kubernetes TESTARGS='-run=TestAccKubernetesNetworkPolicy_*' 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./kubernetes -v -run=TestAccKubernetesNetworkPolicy_* -timeout 120m
=== RUN   TestAccKubernetesNetworkPolicy_basic
--- PASS: TestAccKubernetesNetworkPolicy_basic (0.40s)
=== RUN   TestAccKubernetesNetworkPolicy_importBasic
--- PASS: TestAccKubernetesNetworkPolicy_importBasic (0.11s)
PASS
ok      github.com/terraform-providers/terraform-provider-kubernetes/kubernetes 0.590s
```

**Comment by pdecat** [comment]
I guess a diff suppression function is needed to avoid detection of changes when protocol is not specified:

```
  ~ kubernetes_network_policy.my-policy
      spec.0.ingress.0.ports.0.protocol: "TCP" => ""
```

**Comment by acobaugh** [comment]
Can we get this merged? I started working on this myself then found this PR. This would help me implement some micro-segmentation-style patterns in my clusters.

**Comment by paultyng** [comment]
@pdecat that refactor I think we could move through a little faster if you want to split it to a new PR?

**Comment by pdecat** [comment]
@paultyng, good point, done: #140

**Comment by pdecat** [comment]
Superseded by https://github.com/terraform-providers/terraform-provider-kubernetes/pull/118 now that is merged.

**Pull request closed without merging**
